### PR TITLE
Add methods for Badge Arcade (WIP)

### PR DESCRIPTION
**Pull request by DaniElectra**
Hello! I want to contribute to Pretendo Network, and I'm currently working on NEX servers for Badge Arcade.

This pull request adds the necessary methods for Nintendo Badge Arcade servers to function.

Note that this PR is marked as draft, as I haven't tested the functions properly because I'm having some errors when connecting the console to the servers.

### CODE REVIEW

**Comment by shutterbug2000** [comment]
Hi!
At a quick glance, this seems pretty solid (although I haven't taken a super close look :p)
One thing I do wanna bring up is that the implementation of SecureProtocol does not have GetMaintenanceStatus in most games, so it should be made it's own file similar to Datastore.

**Comment by DaniElectra** [comment]
> Hi! At a quick glance, this seems pretty solid (although I haven't taken a super close look :p) One thing I do wanna bring up is that the implementation of SecureProtocol does not have GetMaintenanceStatus in most games, so it should be made it's own file similar to Datastore.

Thanks for reviewing this! Ok, I implemented the Secure method on a new file, so that should be fixed.

Btw, as you may have seen in the commit, we need to implement Custom ID support on `RMCResponse` for the Shop protocol. Should I create a new function for that (like `SetCustomID()`) or modify the `NewRMCResponse()` function?

**Comment by jonbarrow** [comment]
I'm not sure what you mean? The RMC structs in `nex-go` already support extended (custom) protocol IDs? Both requests and responses, so I'm not sure what the issue is?

**Comment by DaniElectra** [comment]
I mean setting the Custom ID. `RMCResponse` does not have getters and setters for the parameters, so it's currently not possible to set a Custom ID to the response (to my knowledge)

**Comment by jonbarrow** [comment]
Oh! I just double checked and you're right. There's support for encoding the data correctly but not for actually setting it

Yes a new PR is fine, just make getter/setters for customID since the Bytes() method already checks if protocolID is 0x7f, and then writes the customID if so

Then when making responses just make a new RMCRespons with the protocolID 0x7f and use the setter for customID before calling Bytes()

It's already designed to handle the rest

**Comment by jonbarrow** [comment]
Your PR has been merged

**Comment by jonbarrow** [comment]
Looks good 👍

**Comment by DaniElectra** [comment]
Oh, thanks for merging! Btw, below I'll leave the link to the repositories of the servers for Badge Arcade that I'm working on. It's still in development and there are some bugs, but it would be nice if we could get it into Pretendo soon:

Authentication server: https://github.com/DaniElectra/badge-arcade-authentication

Secure server: https://github.com/DaniElectra/badge-arcade-secure

**Comment by jonbarrow** [comment]
Thank you, but we have actually already been talking internally about Badge Arcade 🙂 we've been debating how to handle it legally for months now

**Comment by DaniElectra** [comment]
Well, from my research the NEX servers don't store any image data, just a reference to the badges, so I think copyright wouldn't be an issue if we want to use the original badges (until Nintendo decides to drop the BOSS data from their servers).

**Comment by jonbarrow** [comment]
The issue is that Nintendos badges are supposed to be obtained after paying money for plays. We cannot charge money for games, and we cannot provide Nintendos badges for free as they could strike us down for that. So we are exploring using custom badges

**Comment by DaniElectra** [comment]
I see. I've taken a brief look at the badges data (not a lot, I've been working mainly on the servers) and how custom badges could be implemented. Could I try to help with this?

I'm on Discord, if you are fine with it

**Pull request merged**
