### PR TITLE
datastore/pokemon-gen6: Add missing handler for PrepareUploadPokemon

### PR DESCRIPTION
**Pull request by ItzSwirlz**
hello! I'm new to all this... from what I can understand these are just **handlers** and just pass things to the actual function implementation.

Reference: https://github.com/kinnay/NintendoClients/wiki/Data-Store-Protocol-(Pokemon-XY)#40-prepareuploadpokemon

### CODE REVIEW

**Comment by DaniElectra** [comment]
Nice catch! The code itself looks good, but were planning to move the game-specific patches of protocols to the servers themselves. I will bring up @jonbarrow for thoughts

**Comment by ItzSwirlz** [comment]
> Nice catch! The code itself looks good, but were planning to move the game-specific patches of protocols to the servers themselves. I will bring up @jonbarrow for thoughts

_it was a copy and paste btw_

**Comment by jonbarrow** [comment]
> I will bring up @jonbarrow for thoughts

Correct, our plans moving forward are to remove all game-specific handlers from this module and instead implement them in their respective servers

That being said, we have not officially started this migration yet, and it will be done on a per-server basis (we can't move stuff from here to servers that don't exist yet). So for now this can be merged

**Review by DaniElectra — APPROVED** [review]

**Comment by ItzSwirlz** [comment]
FYI: I have **zero** experience in server development, so, uh, lol

I'm going through all the methods in the documentation, if I spot any missing handlers ill lyk know

**Comment by jonbarrow** [comment]
> I'm going through all the methods in the documentation

There shouldn't be that many missing. But for what it's worth, we maintain a more up-to-date version of that wiki here https://nintendo-wiki.pretendo.network/docs/

We make issues and PRs regarding new information to bring our findings back upstream into Kinnay's wiki, but he (understandably) seems more interested in the Switch these days. So sometimes our information differs

**Pull request merged**
